version: '3'

services:
    db:
        image: postgres:13.1
        ports:
            - "5432:5432"
        restart: unless-stopped
        command: >
            -c ssl=on
            -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
            -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
        environment:
            - POSTGRES_PASSWORD=joplin
            - POSTGRES_USER=joplin
            - POSTGRES_DB=joplin
    app:
        image: joplin:test
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_BASE_URL=http://localhost:22300
            - APP_PORT=22300
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=joplin
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=joplin
            - POSTGRES_HOST=db
            - POSTGRES_SSL_ENABLE=true
            - POSTGRES_SSL_VERIFY=false
